services:
  fake-twitter-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - fake-twitter-volume:/var/www/html
    ports:
      - "9000:9000"
    environment:
      - MYSQL_HOST=db-mariadb
      - MYSQL_DATABASE=dbfaketwitter
      - MYSQL_USERNAME=root
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DB_PORT=3306
    container_name: fake-twitter-backend-container
  fake-twitter-nginx:
    image: nginx:alpine
    volumes:
      - fake-twitter-volume:/var/www/html
      - ./vhost.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:9000"
    depends_on:
      - fake-twitter-fpm
    container_name: fake-twitter-nginx-container
volumes:
  fake-twitter-volume:
